# This deploys all the required components to start McM
# The database, the search engine and the application
services:
  mcm-couchdb:
    image: docker.io/couchdb:3.3.3@sha256:b8c85ebce55d1c0c676ce7a9beaff87f514c0df25afd5fa844e744985c0c2fd1
    environment:
      - NODENAME=${COUCHDB_NODENAME}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - ${COUCHDB_DATA}:/opt/couchdb/data
    networks:
      - mcm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  mcm-couchdb-wizard:
    image: docker.io/library/alpine:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      - mcm-couchdb
    command: |
      sh -c 'apk add curl &&
             curl -s -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@mcm-couchdb:5984/_users &&
             curl -s -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@mcm-couchdb:5984/_replicator &&
             curl -s -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@mcm-couchdb:5984/_global_changes' &&
             exit 0
    networks:
      - mcm
    
  mcm-couchdb-lucene:
    image: docker.io/pdmvserv/couchdb-lucene:2.2.0@sha256:efdde9c34c2d3ce3896f25289e02001b258452e1a8931bba31a01c78c074d1be
    volumes:
      - ${LUCENE_DATA_PATH}:/opt/couchdb-lucene/indexes
      - ${LUCENE_CONF_PATH}:/opt/couchdb-lucene/conf
    ports:
      - ${LUCENE_PORT}:5985
    depends_on:
      - mcm-couchdb
    networks:
      - mcm

  mcm-application:
    build: ${MCM_DOCKERFILE_PATH}
    environment:
      - MCM_DEBUG=True
      - MCM_WARMUP_SECONDS=${MCM_WARMUP_SECONDS}
      - MCM_COUCHDB_URL=${MCM_COUCHDB_URL}
      - COUCH_CRED=${COUCH_CRED}
      - MCM_LUCENE_URL=${MCM_LUCENE_URL}
    command: |
      /bin/bash -c '
        echo "Warming up for $MCM_WARMUP_SECONDS seconds";
        sleep $MCM_WARMUP_SECONDS; 
        echo "Starting McM...";
        python main.py'
    ports:
      - "${MCM_PORT}:8000"
    depends_on: 
      - mcm-couchdb
      - mcm-couchdb-lucene
    networks:
      - mcm

networks:
  mcm: